HUSTLE-UMC/HUSTLE_web

hustle_web/src/components/SportsButton/ButtonProps.ts, hustle_web/src/components/SportsButton/SportsButton.tsx, hustle_web/src/components/SportsButton/Styles.tsx, hustle_web/src/components/SportsMenu/SportsMenu.tsx, hustle_web/src/components/SportsMenu/Styles.tsx, hustle_web/src/recoil/SportsButton.tsx, hustle_web/src/stories/SportsButton/SportsButton.stories.ts
#34 운동 메뉴 스타일 수정
-[ ] 운동 메뉴 스타일 변경
카테고리 화면과 같이 수정되었습니다. 코드에 큰 변동사항은 없습니다
=> [Style] - #34 운동버튼 스타일수정

hustle_web/src/Router.tsx, hustle_web/src/components/SignIn/SignIn.tsx, hustle_web/src/components/SignIn/Styles.ts, hustle_web/src/pages/SignIn/Styles.tsx, hustle_web/src/pages/SignIn/index.tsx, hustle_web/src/routes.ts
=> Refactor: 회원가입 화면 리펙토링

hustle_web/src/components/MatchButton/MatchButton.tsx, hustle_web/src/components/MatchButton/MatchButtonProps.ts, hustle_web/src/components/MatchButton/Styles.ts, hustle_web/src/components/MatchStatus/MatchStatus.tsx, hustle_web/src/components/MatchStatus/MatchStatusProps.ts, hustle_web/src/components/MatchStatus/Styles.ts, hustle_web/src/stories/MatchButton/MatchButton.stories.tsx, hustle_web/src/stories/MatchStatus/MatchStatus.stories.tsx, hustle_web/src/styles/Color.ts
#16 공식대회 화면 구성
리디자인 및 페이지 생성중입니다.
=> Design/#16 공식대회 화면 구성

hustle_web/src/components/RankList/RankList.tsx, hustle_web/src/components/RankList/RankListProps.ts, hustle_web/src/components/RankList/Styles.ts, hustle_web/src/stories/RankList/RankList.stories.tsx
#63 랭킹 페이지 제작
npm run storybook으로 RankList 확인가능
li 태그와 span 태그로 수정중이라 스타일 적용중
=> Feat63: 랭킹 컴포넌트 제작(수정중)

hustle_web/src/Router.tsx, hustle_web/src/components/CompetitionInfo/Content/Content.tsx, hustle_web/src/components/CompetitionInfo/Content/ContentProps.ts, hustle_web/src/components/CompetitionInfo/Content/Styles.ts, hustle_web/src/components/CompetitionInfo/Title/Styles.ts, hustle_web/src/components/CompetitionInfo/Title/Title.tsx, hustle_web/src/components/CompetitionInfo/Title/TitleProps.ts, hustle_web/src/components/MatchList/MatchList.tsx, hustle_web/src/components/MatchList/MatchListProps.ts, hustle_web/src/components/MatchList/Styles.ts, hustle_web/src/components/TeamInfo/Styles.ts, hustle_web/src/components/TeamInfo/TeamInfo.tsx, hustle_web/src/pages/Competition/Competition.tsx, hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx, hustle_web/src/pages/Competition/CompetitionApply/Styles.ts, hustle_web/src/pages/Competition/Styles.ts, hustle_web/src/routes.ts, hustle_web/src/stories/Content/Content.stories.tsx, hustle_web/src/stories/MatchList/MatchList.stories.tsx, hustle_web/src/stories/Title/Title.stories.tsx
#65 랭킹 상세 페이지 디자인
-[ ] 상세 디테일 수정중입니다
-[ ]
=> Design/#65 랭킹 상세 페이지 디자인

hustle_web/src/components/FriendlyMatchPage/ApplyMatch/ApplyMatch.tsx, hustle_web/src/components/FriendlyMatchPage/MatchDetail/MatchDetail.tsx, hustle_web/src/components/FriendlyMatchPage/MatchDetail/Styles.tsx
=> Fix: 교류전 상세페이지 화면 수정

hustle_web/src/components/MainCompetition/ApplyForm/ApplyForm.tsx, hustle_web/src/components/MainCompetition/ApplyForm/DummyCompetition.tsx, hustle_web/src/components/MainCompetition/PostCompetition/PostCompetition.tsx, hustle_web/src/components/SignIn/DummyUniversityData.tsx, hustle_web/src/components/SignIn/GenderButton.tsx, hustle_web/src/components/SignIn/SignIn.tsx, hustle_web/src/components/SignIn/Styles.ts, hustle_web/src/components/SignIn/UniversitySearch.tsx, hustle_web/src/constants/defaultFormOption.ts, hustle_web/src/constants/interfaces.ts
fix/#70 성별 기능 추가
대학 검색 기능은 현재 수정 중입니다.
=> fix/#70 성별 기능 추가

hustle_web/src/components/MainCompetition/ApplyForm/ApplyForm.tsx, hustle_web/src/components/MainCompetition/ApplyForm/Styles.tsx, hustle_web/src/pages/MainCompetition/ApplyCompetition.tsx
대회 신청하기 정렬 스타일 수정, sportsmenu 제거
=> Feat/#71 대회 신청하기 정렬 스타일 수정, sportsmenu 제거

hustle_web/src/components/Forgot/FIndPW/FindPW.tsx, hustle_web/src/components/Forgot/FindID/FindID.tsx
=> [Fix] - axios 수정

hustle_web/src/components/CompetitionPage/CompetitionDetail/CompetitionDetail.tsx, hustle_web/src/components/CompetitionPage/CompetitionDetail/Styles.ts, hustle_web/src/pages/Competition/CompetitionDetailResult/CompetitionDetailResult.tsx, hustle_web/src/recoil/CompetitionPage/states.tsx, hustle_web/src/recoil/CompetitionPage/types.tsx
=> Fix83: 개인 득점 현황 관련 상태값 수정

hustle_web/src/pages/Home/Styles.tsx, hustle_web/src/pages/Home/index.tsx
=> Feat88: 메인화면 랭킹 추가

hustle_web/src/Router.tsx, hustle_web/src/components/CompetitionDropDown/DropDown.tsx, hustle_web/src/components/CompetitionDropDown/Styles.tsx, hustle_web/src/components/CompetitionPage/CompetitionDetail/CompetitionDetail.tsx, hustle_web/src/components/CompetitionPage/CompetitionDetail/Styles.ts, hustle_web/src/components/CompetitionPage/CompetitionInput/CompetitionInput.tsx, hustle_web/src/components/CompetitionPage/CompetitionInput/Styles.ts, hustle_web/src/components/CompetitionPage/TimeTableList/Styles.ts, hustle_web/src/components/CompetitionPage/TimeTableList/TimeTableList.tsx, hustle_web/src/pages/Competition/CompetitionDetailResult/CompetitionDetailResult.tsx, hustle_web/src/pages/Competition/CompetitionInput/CompetitionInput.tsx, hustle_web/src/pages/Competition/CompetitionInputPage/CompetitionInputPage.tsx, hustle_web/src/recoil/CompetitionPage/states.tsx, hustle_web/src/recoil/Ranking/rankingLists.tsx, hustle_web/src/routes.ts
=> Fix/#87 대회 상세 결과 화면 수정

hustle_web/src/components/MatchList/MatchList.tsx, hustle_web/src/components/MatchStatus/MatchStatus.tsx, hustle_web/src/components/MatchStatus/MatchStatusProps.ts, hustle_web/src/recoil/MatchList.tsx, hustle_web/src/stories/MatchStatus/MatchStatus.stories.tsx
#93 
-[ ] response.data.data
-[ ] .data를 두번써야해요
=> Feat/#93 대회 보기 화면 연동

hustle_web/package-lock.json, hustle_web/package.json, hustle_web/src/pages/Home/index.tsx, hustle_web/src/recoil/hotcompetitionList.tsx
=> Feat90: 메인화면 Hot 대회 연동

hustle_web/src/components/CompetitionPage/CompetitionButton/MainCompetitionButton.tsx, hustle_web/src/components/CompetitionPage/CompetitionButton/PreCompetitionButton.tsx, hustle_web/src/components/CompetitionPage/MainList/MainList.tsx, hustle_web/src/components/CompetitionPage/PreList/PreList.tsx, hustle_web/src/recoil/CompetitionPage/CompetitionButton.tsx, hustle_web/src/recoil/CompetitionPage/selectors.tsx
closed #100 
-[ ] 예선 , 본선 선택에 따른 렌더링 로직 수정
=> Fix : 대회결과 리스트 출력 수정

hustle_web/package-lock.json, hustle_web/package.json, hustle_web/src/Router.tsx, hustle_web/src/components/MainCompetition/PostCompetition/PostCompetition.tsx, hustle_web/src/components/MatchList/MatchList.tsx, hustle_web/src/components/MatchList/Styles.ts, hustle_web/src/components/PostMatchButton/PostMatchButton.tsx, hustle_web/src/components/PostMatchButton/PostMatchButtonProps.tsx, hustle_web/src/components/PostMatchButton/Styles.ts, hustle_web/src/constants/defaultFormOption.ts, hustle_web/src/constants/interfaces.ts, hustle_web/src/pages/Competition/Competition.tsx, hustle_web/src/pages/Competition/Styles.ts, hustle_web/src/pages/Home/index.tsx, hustle_web/src/recoil/hotcompetitionList.tsx, hustle_web/src/routes.ts
#102 대회화면 개설버튼 추가
-[ ] 개설 버튼 추가
-[ ] 버튼 navigate 연동
=> Feat102: 대회화면 개설버튼 추가 / 개설 API 연동

hustle_web/src/Router.tsx, hustle_web/src/components/CompetitionInfo/Title/Styles.ts, hustle_web/src/components/CompetitionInfo/Title/Title.tsx, hustle_web/src/components/MatchList/MatchList.tsx, hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx, hustle_web/src/pages/Competition/CompetitionApply/Styles.ts, hustle_web/src/recoil/MatchList.tsx, hustle_web/src/routes.ts
=> Feat99: 대회 신청하기 화면 연동

hustle_web/src/components/MainCompetition/PostCompetition/PostCompetition.tsx
fix109: posterUrl 더미값 변경
-[ ] fix109: posterUrl 더미값 변경
=> fix109: posterUrl 더미값 변경

hustle_web/src/components/Content/Styles.tsx, hustle_web/src/components/MatchStatus/Styles.ts, hustle_web/src/pages/Home/Styles.tsx
#108 푸터 위치 조정 및 대회 출력 화면 스타일 조정
=> Fix/#108 푸터 위치 조정

hustle_web/src/Router.tsx, hustle_web/src/components/Community/Club/ClubMain.tsx, hustle_web/src/components/Community/Main/Lists.tsx, hustle_web/src/components/Community/Main/MainCommunity.tsx, hustle_web/src/components/Community/Main/MatchList.tsx, hustle_web/src/components/Community/Main/MatchMenu.tsx, hustle_web/src/components/Community/Question/QuestionList.tsx, hustle_web/src/components/Community/Question/QuestionStyle.ts, hustle_web/src/components/Login/Kakao/KakaoLogin.tsx, hustle_web/src/components/Login/Login.tsx, hustle_web/src/constants/interfaces.ts, hustle_web/src/pages/Community/CommunityPage.tsx, hustle_web/src/recoil/community.tsx, hustle_web/src/routes.ts
=> [Fix] - 카카오로그인 추가, 커뮤니티 페이지 수정

hustle_web/src/Router.tsx, hustle_web/src/components/MainCompetition/ApplyForm/CompetitionApplyForm.tsx, hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx, hustle_web/src/routes.ts
feat107: 대회 신청 API 연동
-[] 대회 신청 API 연동
=> feat107: 대회 신청 API 연동

hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx, hustle_web/src/recoil/MatchList.tsx
=> Fix: 대회 신청 정보 화면 사진 출력 수정

hustle_web/src/components/Login/Login.tsx, hustle_web/src/constants/FormRequirements.ts, hustle_web/src/constants/interfaces.ts
=> [Fix] - 로그인 성공

hustle_web/src/components/MatchStatus/MatchStatus.tsx, hustle_web/src/components/MatchStatus/Styles.ts, hustle_web/src/pages/Competition/CompetitionApply/CompetitionApply.tsx
=> Feat/#118 디테일 수정

hustle_web/src/components/MainCompetition/ApplyForm/CompetitionApplyForm.tsx, hustle_web/src/components/MainCompetition/PostCompetition/PostCompetition.tsx
신청 로직 수정
-[ ] 신청 로직 수정
신청 로직 수정
=> fix123: 신청 로직 수정

hustle_web/src/Router.tsx, hustle_web/src/components/Login/Kakao/KakaoLogin.tsx, hustle_web/src/components/Login/Login.tsx, hustle_web/src/pages/KakaoLogin/KakaoLogin.tsx, hustle_web/src/routes.ts
=> [Fix] - 카카오로그인 수정

hustle_web/src/components/Content/Styles.tsx, hustle_web/src/components/Footer/FooterStyles.ts, hustle_web/src/components/FriendlyMatchPage/ApplyMatch/ApplyForm.tsx, hustle_web/src/components/FriendlyMatchPage/LocationBox/LocationBox.tsx, hustle_web/src/components/FriendlyMatchPage/LocationBox/currentLocation.ts, hustle_web/src/components/FriendlyMatchPage/MainMatch/FriendlyLists/FriendlyLists.tsx, hustle_web/src/components/FriendlyMatchPage/MainMatch/FriendlyLists/InvitationLists.tsx, hustle_web/src/components/FriendlyMatchPage/MainMatch/FriendlyLists/MatchLists.tsx, hustle_web/src/components/FriendlyMatchPage/MainMatch/Styles.tsx, hustle_web/src/components/FriendlyMatchPage/MatchDetail/Location.tsx, hustle_web/src/components/FriendlyMatchPage/MatchDetail/MatchDetail.tsx, hustle_web/src/components/FriendlyMatchPage/MatchDetail/Styles.tsx, hustle_web/src/components/FriendlyMatchPage/PageButton/Styles.ts, hustle_web/src/components/FriendlyMatchPage/PostMatch/InvitationForm.tsx, hustle_web/src/components/FriendlyMatchPage/PostMatch/MatchForm.tsx, hustle_web/src/components/MatchList/MatchList.tsx, hustle_web/src/components/SportsMenu/SportsMenu.tsx, hustle_web/src/constants/defaultFormOption.ts, hustle_web/src/constants/interfaces.ts, hustle_web/src/pages/FriendlyMatch/FriendlyMatch.tsx, hustle_web/src/pages/Home/index.tsx, hustle_web/src/recoil/SportsButton.tsx, hustle_web/src/recoil/friendlyMatchPage/selectors.tsx, hustle_web/src/recoil/friendlyMatchPage/states.tsx, hustle_web/src/recoil/friendlyMatchPage/types.tsx
#85 
불명확한 파라미터들은 일단 하드코딩으로 작성했습니다
교류전 지원 api 연동은 아직 미완성상태입니다
=> Feat/#85 교류전 조회, 개설 api 연동

hustle_web/src/components/SignIn/SignIn.tsx, hustle_web/src/components/SignIn/UniversitySearch.tsx, hustle_web/src/constants/interfaces.ts
회원가입 기능 구현
localhost:3000에서 돌려주세요
=> fix/#122: 회원가입 기능 구현

hustle_web/src/recoil/Ranking/rankingLists.tsx
feat127: 랭킹 정보 수정
-[ ] feat127: 랭킹 정보 수정
=> feat127: 랭킹 정보 수정

hustle_web/src/App.tsx, hustle_web/src/components/Auth/AuthProvider.tsx, hustle_web/src/components/Auth/LoginComponent.tsx, hustle_web/src/components/Header/Styles.tsx, hustle_web/src/components/Header/index.tsx, hustle_web/src/components/Login/Login.tsx, hustle_web/src/components/SignIn/SignIn.tsx, hustle_web/src/constants/defaultFormOption.ts, hustle_web/src/constants/interfaces.ts, hustle_web/src/recoil/login/login.ts
=> fix132: 로그인/로그아웃 수정
